### ISSUE TITLE
CYRILLIC merge: GRAD masters cleanup

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/googlesans#456]
Cyrillic GRAD masters update. 
I cleaned up contour/interpolation issues in Cyrillic GRAD masters, 
and also adjusted `C`, `c`, `c.sc` glyphs, since they are required for Cyrillic components. 

My .glyphs files don't convert to UFOs: 
(Removing background didn't help.)

```
Traceback (most recent call last):
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/gs-glyphs2ufo.py", line 76, in <module>
    normalize.scrub_designspace(designspace, ROOT_DIR)
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/internal/normalize.py", line 40, in scrub_designspace
    ot_categories = infer_opentype_categories(designspace.default.font)
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/internal/normalize.py", line 301, in infer_opentype_categories
    pf(font=ufo_copy)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 12, in __call__
    if super().__call__(font, glyphSet):
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/base.py", line 195, in __call__
    if include(glyph) and filter_(glyph):
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 24, in filter
    flattened_tuples = _flattenComponent(self.context.glyphSet, comp)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
[Google-Sans-Cyrillic.zip](https://github.com/googlefonts/googlesans/files/8098955/Google-Sans-Cyrillic.zip)

  [Previous line repeated 987 more times]
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 40, in _flattenComponent
    if not glyph.components or len(glyph) > 0:
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufoLib2/objects/glyph.py", line 86, in __len__
    return len(self.contours)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Notes on the Cyrillic edits here: https://github.com/googlefonts/googlesans/issues/449

**Comment by alexeiva** [comment]
I will provide a glyph list and run fontmake on the glyphs sources

**Comment by alexeiva** [comment]
1. `fontmake -g GoogleSans-Cyrillic.glyphs` complained about y.bracket.18 layer, so I removed the bracket layers on y. This resolved the masters compatibility issue. All Cyrillic glyphs are compatible. 

2. Still get the recursion depth error. 
```
fontmake -g GoogleSans-Cyrillic.glyphs
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "GoogleSans-Cyrillic.glyphs" file into <GSFont>
INFO:fontmake.font_project:Building OTF for GoogleSans-Bold
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters.base:Running PropagateAnchorsFilter on GoogleSans-Bold
INFO:ufo2ft.filters.base:Running FlattenComponentsFilter on GoogleSans-Bold
fontmake: Error: In 'GoogleSans-Cyrillic.glyphs' -> 'master_ufo/GoogleSans.designspace' -> 'master_ufo/GoogleSans-opsz18-wght734-GRAD0.ufo': Compiling UFO failed: maximum recursion depth exceeded while calling a Python object
```

3. The UFOs were still generated. I uploaded them here: https://github.com/googlefonts/googlesans/tree/alexeiva-cyr-GRAD-fix/source/GoogleSans

**Comment by alexeiva** [comment]
List of glyphs updated:

[GoogleSans-Cyrillic.txt](https://github.com/googlefonts/googlesans/files/8146163/GoogleSans-Cyrillic.txt)

Glyphs `Dje` `dje-cy.sc` need re-importing basic (non-GRAD) masters for roman and italic, 
because there was a design-bug:

<img width="426" alt="153760144-cd71b053-56c4-471b-a74e-efdf002c894e" src="https://user-images.githubusercontent.com/16634089/155835315-db17868e-0ddf-4c3c-871f-5f1c48c60101.png">

**Comment by chrissimpkins** [comment]
Thank you very much Alexei.  I really appreciate all of your work on these updates.  I'll discuss the Latin changes here with @dberlow and we'll be in touch if he has questions or we need to edit things further.

The Fonts engineering team have asked that we not push new production Latin design edits until the release at the end of Q2.  We'll plan to import your work during the second quarter and target this for the Google Sans v9 release due out in early summer.

**Comment by alexeiva** [comment]
UPDATE: Fixed https://github.com/googlefonts/googlesans/issues/399

.glyphs archive
[GoogleSans-Cyrillic.zip](https://github.com/googlefonts/googlesans/files/8247228/GoogleSans-Cyrillic.zip)
